name: pytest
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv codecov
        pip install -r requirements.txt
        pipenv install --dev
    - name: Build bcftools
      run: |
        wget https://github.com/samtools/bcftools/releases/download/1.18/bcftools-1.18.tar.bz2
        tar xf bcftools-1.18.tar.bz2
        cd bcftools-1.18
        ./configure --prefix=/usr/local/bin
        sudo make
        sudo make install
        export PATH=/usr/local/bin:$PATH
    - name: Build htslib
      run: |
        wget https://github.com/samtools/htslib/releases/download/1.18/htslib-1.18.tar.bz2
        tar xf htslib-1.18.tar.bz2
        cd htslib-1.18
        ./configure --prefix=/usr/local/bin
        sudo make
        sudo make install
        export PATH=/usr/local/bin:$PATH
    - name: Test with pytest
      run: |
        export BCFTOOLS_PLUGINS=/usr/local/libexec/bcftools
        pytest -vv --cov resources/